### ISSUE TITLE
footer padding

### ISSUE THREAD

**Issue by sumi-0011** [jeonbyeongmin/yum#6]
![image](https://user-images.githubusercontent.com/49177223/168644655-358dbbb7-cfd2-41ee-8c6a-13282efb7a3d.png)

padding-bottom도 있는건 의도한건가요?!

**Comment by jeonbyeongmin** [comment]
아 혹시 나중에 footer 색깔 변경할 수도 있으니까 엘레멘트들 가운데에 두려고 일부로 설정했어
